spring:
  datasource:
    password: postgres
    username: postgres
    url: "jdbc:postgresql://localhost:5432/fitapp"
  jpa:
    hibernate:
      ddl-auto: update


jwt:
  http-header: "Authorization"
  token-prefix: "Bearer "
  expirationTime: 3600000
  secret: "secret"